version: '3'
services:
  envoy:
    build:
      context: ./
      dockerfile: ./envoy.Dockerfile
    image: bookservice/envoy
    ports:
      - "8085:8085"
    networks:
      - apps
networks:
  apps:
    driver: host
