# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Book.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Book.proto',
  package='book',
  syntax='proto3',
  serialized_options=_b('\n\023com.muhtar.rpc.bookP\001'),
  serialized_pb=_b('\n\nBook.proto\x12\x04\x62ook\"L\n\x0b\x42ookMessage\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x0c\n\x04isbn\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\"2\n\x0f\x42ookMessageList\x12\x1f\n\x04\x62ook\x18\x01 \x03(\x0b\x32\x11.book.BookMessage\"\x07\n\x05\x45mpty2\xaa\x01\n\x0b\x42ookService\x12-\n\x07\x66indAll\x12\x0b.book.Empty\x1a\x15.book.BookMessageList\x12;\n\x0f\x66indBookByQuery\x12\x11.book.BookMessage\x1a\x15.book.BookMessageList\x12/\n\x07\x61\x64\x64\x42ook\x12\x11.book.BookMessage\x1a\x11.book.BookMessageB\x17\n\x13\x63om.muhtar.rpc.bookP\x01\x62\x06proto3')
)




_BOOKMESSAGE = _descriptor.Descriptor(
  name='BookMessage',
  full_name='book.BookMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='book.BookMessage.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='author', full_name='book.BookMessage.author', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isbn', full_name='book.BookMessage.isbn', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='category', full_name='book.BookMessage.category', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=96,
)


_BOOKMESSAGELIST = _descriptor.Descriptor(
  name='BookMessageList',
  full_name='book.BookMessageList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='book', full_name='book.BookMessageList.book', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=148,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='book.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=157,
)

_BOOKMESSAGELIST.fields_by_name['book'].message_type = _BOOKMESSAGE
DESCRIPTOR.message_types_by_name['BookMessage'] = _BOOKMESSAGE
DESCRIPTOR.message_types_by_name['BookMessageList'] = _BOOKMESSAGELIST
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BookMessage = _reflection.GeneratedProtocolMessageType('BookMessage', (_message.Message,), {
  'DESCRIPTOR' : _BOOKMESSAGE,
  '__module__' : 'Book_pb2'
  # @@protoc_insertion_point(class_scope:book.BookMessage)
  })
_sym_db.RegisterMessage(BookMessage)

BookMessageList = _reflection.GeneratedProtocolMessageType('BookMessageList', (_message.Message,), {
  'DESCRIPTOR' : _BOOKMESSAGELIST,
  '__module__' : 'Book_pb2'
  # @@protoc_insertion_point(class_scope:book.BookMessageList)
  })
_sym_db.RegisterMessage(BookMessageList)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'Book_pb2'
  # @@protoc_insertion_point(class_scope:book.Empty)
  })
_sym_db.RegisterMessage(Empty)


DESCRIPTOR._options = None

_BOOKSERVICE = _descriptor.ServiceDescriptor(
  name='BookService',
  full_name='book.BookService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=160,
  serialized_end=330,
  methods=[
  _descriptor.MethodDescriptor(
    name='findAll',
    full_name='book.BookService.findAll',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_BOOKMESSAGELIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='findBookByQuery',
    full_name='book.BookService.findBookByQuery',
    index=1,
    containing_service=None,
    input_type=_BOOKMESSAGE,
    output_type=_BOOKMESSAGELIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='addBook',
    full_name='book.BookService.addBook',
    index=2,
    containing_service=None,
    input_type=_BOOKMESSAGE,
    output_type=_BOOKMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BOOKSERVICE)

DESCRIPTOR.services_by_name['BookService'] = _BOOKSERVICE

# @@protoc_insertion_point(module_scope)
