# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Book_pb2 as Book__pb2


class BookServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.findAll = channel.unary_unary(
        '/book.BookService/findAll',
        request_serializer=Book__pb2.Empty.SerializeToString,
        response_deserializer=Book__pb2.BookMessageList.FromString,
        )
    self.findBookByQuery = channel.unary_unary(
        '/book.BookService/findBookByQuery',
        request_serializer=Book__pb2.BookMessage.SerializeToString,
        response_deserializer=Book__pb2.BookMessageList.FromString,
        )
    self.addBook = channel.unary_unary(
        '/book.BookService/addBook',
        request_serializer=Book__pb2.BookMessage.SerializeToString,
        response_deserializer=Book__pb2.BookMessage.FromString,
        )


class BookServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def findAll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def findBookByQuery(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def addBook(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BookServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'findAll': grpc.unary_unary_rpc_method_handler(
          servicer.findAll,
          request_deserializer=Book__pb2.Empty.FromString,
          response_serializer=Book__pb2.BookMessageList.SerializeToString,
      ),
      'findBookByQuery': grpc.unary_unary_rpc_method_handler(
          servicer.findBookByQuery,
          request_deserializer=Book__pb2.BookMessage.FromString,
          response_serializer=Book__pb2.BookMessageList.SerializeToString,
      ),
      'addBook': grpc.unary_unary_rpc_method_handler(
          servicer.addBook,
          request_deserializer=Book__pb2.BookMessage.FromString,
          response_serializer=Book__pb2.BookMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'book.BookService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
